version: '3.7'

services:
  game_engine:
    build: .
    expose:
      - 8000
#    ports:
#      - 8000:8000
    volumes:
      - ./game:/game
    stdin_open: true
    tty: true

  nginx:
    image: nginx
    expose:
      - 80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/default.conf

